### ISSUE TITLE
Decision: How to export modules

### ISSUE THREAD

**Issue by akazakou** [source-config/config#9]
According to [the discussion](https://github.com/source-config/source-config/pull/7#discussion_r233855975), we should make decision how to export modules

**Comment by nlebedevinc** [comment]
I prefer to use `default export` only in a case when it's necessary and not duplicate it in `export` object.

**Comment by akazakou** [comment]
Which one minuses we would have if we will duplicate it not only in default export?

**Comment by akazakou** [comment]
Stale question. Will think about it if it will be a problem
